---
- name: install nginx
  apt:
    name: nginx
    state: present

- name: create log dir owned by user {{ app_user }}
  file:
    path: "{{ app_root_dir }}/log"
    owner: "{{ app_user }}"
    state: directory

- name: remove default nginx placeholder
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: create config file for {{ app_name }} in /sites-available
  template:
    src: nginx_site.conf
    dest: /etc/nginx/sites-available/{{ app_name }}.conf

- name: link config file for {{ app_name }} in /sites-enabled
  file:
    src: /etc/nginx/sites-available/{{ app_name }}.conf
    dest: /etc/nginx/sites-enabled/{{ app_name }}.conf
    state: link

- name: restart nginx
  service:
    name: nginx
    state: restarted
